name: Daily Trading Data Update

on:
  schedule:
    # This runs at 21:00 UTC (4:00 PM EST) every weekday
    - cron: '0 21 * * 1-5'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run trading script
        run: python app.py
      
      - name: Run pipeline
        run: |
          mkdir -p charts
          python app.py
          python plot_data.py
        
      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          
          git commit -m "Automated data and chart update" || exit 0
          git push
